### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by imbillow** [actions/cache#246]
```
Post job cleanup.
/bin/tar -cz -f /home/runner/work/_temp/b509d82a-370d-4f50-b663-c8e4765d95d0/cache.tgz -C /home/runner/.cache/yarn/v6 .
[warning]Cache service responded with 500 during chunk upload.
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'read'
}
```

**Comment by joshmgross** [comment]
We've added some better error handling around this scenario, see https://github.com/actions/cache/pull/305

https://github.com/actions/cache/issues/287 is a related incident.
