### ISSUE TITLE
cache service responded with 503

### ISSUE THREAD

**Issue by markgoho** [actions/cache#440]
``` bash
Post job cleanup.
/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/enroll/enroll --files-from manifest.txt
Warning: uploadChunk (start: 67108864, end: 100663295) failed: Cache service responded with 503
/home/runner/work/_actions/actions/cache/v2/dist/save/index.js:3136
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with ESPIPE: invalid seek, read
    at ReadStream.<anonymous> (/home/runner/work/_actions/actions/cache/v2/dist/save/index.js:3136:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

**Comment by dhadka** [comment]
Thanks for reporting this.  GitHub Actions is experiencing an outage causing a higher number of 503 errors - https://www.githubstatus.com/.  

I filed a separate issue to fix the cache action so it doesn't fail when 503s happen: https://github.com/actions/cache/issues/441.

**Comment by dhadka** [comment]
Should be resolved as of 23:11 UTC - https://www.githubstatus.com/incidents/k46g5dn2c4lt.

**Comment by ntrifunovic** [comment]
Hi @dhadka: I am also getting similar error now:

```
usr/bin/docker exec  8504af20df9d9383ca557873dbb03b2b50b52e93d2a194821ab71f2b8a75465a sh -c "cat /etc/*release | grep ^ID"
/bin/tar --posix -z -cf cache.tgz -P -C /__w/prime/prime --files-from manifest.txt
Warning: uploadChunk (start: 67108864, end: 100663295) failed: Cache service responded with 503
/__w/_actions/actions/cache/v2/dist/save/index.js:3136
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/__w/_actions/actions/cache/v2/dist/save/index.js:3136:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

**Comment by ntrifunovic** [comment]
I have managed to get this to work by adding `upload-chunk-size: 1000000`.

`upload-chunk-size` should have better documentation and error message might refer to it :smiley:

**Comment by dhadka** [comment]
@ntrifunovic Filed https://github.com/actions/cache/issues/447 with your suggestion to improve the documentation and/or error message.
