### ISSUE TITLE
Bad file descriptor on post-cache upload

### ISSUE THREAD

**Issue by vadi2** [actions/cache#711]
This error has started popping up fairly frequently recently:

```
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/Mudlet/Mudlet --files-from manifest.txt
Warning: uploadChunk (start: 33554432, end: 67108863) failed: Cache service responded with 503
/home/runner/work/_actions/pat-s/always-upload-cache/v2.1.5/dist/save/index.js:4065
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/home/runner/work/_actions/pat-s/always-upload-cache/v2.1.5/dist/save/index.js:4065:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

**Comment by bishal-pdMSFT** [comment]
@vadi2 is this still happening? We had some issues earlier in the cache backend.

**Comment by vadi2** [comment]
I think it's good now! Thanks.
