### ISSUE TITLE
Can No Longer Use From ESM JavaScript Actions

### ISSUE THREAD

**Issue by Kurt-von-Laven** [actions/cache#949]
v3.0.0 was compatible with ESM, but v3.0.4 is not. See ScribeMD/docker-cache#176, which bumps the version of `@actions/cache`. Here is the error we encountered when attempting to upgrade:

```
undefined:1
require
^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/docker-cache/docker-cache/dist/main/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at eval (eval at 8233 (file:///home/runner/work/docker-cache/docker-cache/dist/main/index.js:202:146[7](https://github.com/ScribeMD/docker-cache/actions/runs/3177282360/jobs/5177539082#step:6:8)15), <anonymous>:1:1)
    at Object.[8](https://github.com/ScribeMD/docker-cache/actions/runs/3177282360/jobs/5177539082#step:6:9)233 (file:///home/runner/work/docker-cache/docker-cache/dist/main/index.js:202:146715)
    at __nccwpck_require__ (file:///home/runner/work/docker-cache/docker-cache/dist/main/index.js:202:683[9](https://github.com/ScribeMD/docker-cache/actions/runs/3177282360/jobs/5177539082#step:6:10)64)
    at Object.8020 (file:///home/runner/work/docker-cache/docker-cache/dist/main/index.js:1:36017)
    at __nccwpck_require__ (file:///home/runner/work/docker-cache/docker-cache/dist/main/index.js:202:683964)
    at Object.4580 (file:///home/runner/work/docker-cache/docker-cache/dist/main/index.js:1:26360)
    at __nccwpck_require__ (file:///home/runner/work/docker-cache/docker-cache/dist/main/index.js:202:683964)
    at Object.5798 (file:///home/runner/work/docker-cache/docker-cache/dist/main/index.js:1:21695)
    at __nccwpck_require__ (file:///home/runner/work/docker-cache/docker-cache/dist/main/index.js:202:683964)
    at Object.3971 (file:///home/runner/work/docker-cache/docker-cache/dist/main/index.js:202:[14](https://github.com/ScribeMD/docker-cache/actions/runs/3177282360/jobs/5177539082#step:6:15)4878)
```

**Comment by Phantsure** [comment]
Closing as this seems resolved
